import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";

import { ThemeProviderTW } from "../providers/ThemeProviderTW";
import GlobalNavbar from "@/shared/ui/navbar/GlobalNavbar";

import "./../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <ThemeProviderTW>
            <div className="h-full w-full flex flex-col dark:bg-gray-900 dark:text-white overflow-auto scrollbar-hide">
              <GlobalNavbar />
              {children}
            </div>
          </ThemeProviderTW>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
